
import Foundation

public enum DeviceModel: String, CaseIterable {
    case iPhone3gs = "iPhone 3gs"
    case iPhone4 = "iPhone 4"
    case iPhone4s = "iPhone 4s"
    case iPhone5 = "iPhone 5"
    case iPhone5c = "iPhone 5c"
    case iPhone5s = "iPhone 5s"
    case iPhoneSE1 = "iPhone SE1"
    case iPhone6 = "iPhone 6"
    case iPhone6s = "iPhone 6s"
    case iPhone7 = "iPhone 7"
    case iPhone8 = "iPhone 8"
    case iPhoneSE2 = "iPhone SE2"
    case iPhone12Mini = "iPhone 12 mini"
    case iPhone13Mini = "iPhone 13 mini"
    case iPhone6Plus = "iPhone 6+"
    case iPhone6sPlus = "iPhone 6s+"
    case iPhone7Plus = "iPhone 7+"
    case iPhone8Plus = "iPhone 8+"
    case iPhoneX = "iPhone X"
    case iPhoneXS = "iPhone XS"
    case iPhone11Pro = "iPhone 11 Pro"
    case iPhoneXR = "iPhone XR"
    case iPhone12 = "iPhone 12"
    case iPhone12Pro = "iPhone 12 Pro"
    case iPhone13 = "iPhone 13"
    case iPhone13Pro = "iPhone 13 Pro"
    case iPhoneXSMax = "iPhone XS Max"
    case iPhone11ProMax = "iPhone 11 Pro Max"
    case iPhone12ProMax = "iPhone 12 Pro Max"
    case iPhone13ProMax = "iPhone 13 Pro Max"
    case iPhone16Pro = "iPhone 16 Pro"
    case iPhone16ProMax = "iPhone 16 Pro Max"
}
